# Generated by Django 3.2.4 on 2021-07-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_doccloud_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doccloud',
            name='data',
            field=models.TextField(default='\n    {"style":{"nigthMode":false},"documents":{"value":{}}}'),
        ),
    ]
